export const MATH_SYMBOLS = {
  characters: [
    { id: 1, name: '\\alpha', value: '\\alpha' },
    { id: 2, name: '\\beta', value: '\\beta' },
    { id: 3, name: '\\gamma', value: '\\gamma' },
    { id: 4, name: '\\delta', value: '\\delta' },
    { id: 5, name: '\\epsilon', value: '\\epsilon' },
    { id: 6, name: '\\varepsilon', value: '\\varepsilon' },
    { id: 7, name: '\\zeta', value: '\\zeta' },
    { id: 8, name: '\\eta', value: '\\eta' },
    { id: 9, name: '\\theta', value: '\\theta' },
    { id: 10, name: '\\vartheta', value: '\\vartheta' },
    { id: 11, name: '\\iota', value: '\\iota' },
    { id: 12, name: '\\kappa', value: '\\kappa' },
    { id: 13, name: '\\lambda', value: '\\lambda' },
    { id: 14, name: '\\mu', value: '\\mu' },
    { id: 15, name: '\\nu', value: '\\nu' },
    { id: 16, name: '\\xi', value: '\\xi' },
    { id: 17, name: '\\pi', value: '\\pi' },
    { id: 18, name: '\\rho', value: '\\rho' },
    { id: 19, name: '\\varrho', value: '\\varrho' },
    { id: 20, name: '\\sigma', value: '\\sigma' },
    { id: 21, name: '\\varsigma', value: '\\varsigma' },
    { id: 22, name: '\\tau', value: '\\tau' },
    { id: 23, name: '\\upsilon', value: '\\upsilon' },
    { id: 24, name: '\\phi', value: '\\phi' },
    { id: 25, name: '\\varphi', value: '\\varphi' },
    { id: 26, name: '\\chi', value: '\\chi' },
    { id: 27, name: '\\psi', value: '\\psi' },
    { id: 28, name: '\\omega', value: '\\omega' },
    { id: 29, name: '\\varpi', value: '\\varpi' },
    { id: 30, name: '\\Gamma', value: '\\Gamma' },
    { id: 31, name: '\\Delta', value: '\\Delta' },
    { id: 32, name: '\\Theta', value: '\\Theta' },
    { id: 33, name: '\\Lambda', value: '\\Lambda' },
    { id: 34, name: '\\Xi', value: '\\Xi' },
    { id: 35, name: '\\Pi', value: '\\Pi' },
    { id: 36, name: '\\Sigma', value: '\\Sigma' },
    { id: 37, name: '\\Upsilon', value: '\\Upsilon' },
    { id: 38, name: '\\Phi', value: '\\Phi' },
    { id: 39, name: '\\Psi', value: '\\Psi' },
    { id: 40, name: '\\Omega', value: '\\Omega' },
    { id: 41, name: '\\mathbb{C}', value: '\\mathbb{C}' },
    { id: 42, name: '\\mathbb{P}', value: '\\mathbb{P}' },
    { id: 43, name: '\\mathbb{R}', value: '\\mathbb{R}' },
    { id: 44, name: '\\mathbb{Z}', value: '\\mathbb{Z}' },
    { id: 45, name: '\\mathbb{Q}', value: '\\mathbb{Q}' },
    { id: 46, name: '\\mathbb{N}', value: '\\mathbb{N}' },
    { id: 47, name: '\\mathbb{I}', value: '\\mathbb{I}' },
    { id: 48, name: '\\mathbb{k}', value: '\\mathbb{k}' },
    { id: 49, name: '\\Im', value: '\\Im' },
    { id: 50, name: '\\Re', value: '\\Re' },
    { id: 51, name: '\\aleph', value: '\\aleph' },
    { id: 52, name: '\\beth', value: '\\beth' },
    { id: 53, name: '\\jmath', value: '\\jmath' },
    { id: 54, name: '\\imath', value: '\\imath' },
    { id: 55, name: '\\hbar', value: '\\hbar' }
  ],

  arrows: [
    { id: 1, name: '\\leftarrow', value: '\\leftarrow' },
    { id: 2, name: '\\longleftarrow', value: '\\longleftarrow' },
    { id: 3, name: '\\uparrow', value: '\\uparrow' },
    { id: 4, name: '\\rightarrow', value: '\\rightarrow' },
    { id: 5, name: '\\longrightarrow', value: '\\longrightarrow' },
    { id: 6, name: '\\nearrow', value: '\\nearrow' },
    { id: 7, name: '\\nwarrow', value: '\\nwarrow' },
    { id: 8, name: '\\leftharpoonup', value: '\\leftharpoonup' },
    { id: 9, name: '\\rightharpoonup', value: '\\rightharpoonup' },
    { id: 10, name: '\\mapsto', value: '\\mapsto' },
    { id: 11, name: '\\downdownarrows', value: '\\downdownarrows' },
    { id: 12, name: '\\Uparrow', value: '\\Uparrow' },
    { id: 13, name: '\\downarrow', value: '\\downarrow' },
    { id: 14, name: '\\dashleftarrow', value: '\\dashleftarrow' },
    { id: 15, name: '\\dashrightarrow', value: '\\dashrightarrow' },
    { id: 16, name: '\\searrow', value: '\\searrow' },
    { id: 17, name: '\\swarrow', value: '\\swarrow' },
    { id: 18, name: '\\leftharpoondown', value: '\\leftharpoondown' },
    { id: 19, name: '\\rightharpoondown', value: '\\rightharpoondown' },
    { id: 20, name: '\\longmapsto', value: '\\longmapsto' },
    { id: 21, name: '\\upuparrows', value: '\\upuparrows' },
    { id: 22, name: '\\Downarrow', value: '\\Downarrow' },
    { id: 23, name: '\\upharpoonright', value: '\\upharpoonright' },
    { id: 24, name: '\\upharpoonleft', value: '\\upharpoonleft' },
    { id: 25, name: '\\downharpoonright', value: '\\downharpoonright' },
    { id: 26, name: '\\downharpoonleft', value: '\\downharpoonleft' },
    { id: 27, name: '\\hookleftarrow', value: '\\hookleftarrow' },
    { id: 28, name: '\\hookrightarrow', value: '\\hookrightarrow' },
    { id: 29, name: '\\looparrowleft', value: '\\looparrowleft' },
    { id: 30, name: '\\looparrowright', value: '\\looparrowright' },
    { id: 31, name: '\\leftleftarrows', value: '\\leftleftarrows' },
    { id: 32, name: '\\rightrightarrows', value: '\\rightrightarrows' },
    { id: 33, name: '\\Lleftarrow', value: '\\Lleftarrow' },
    { id: 34, name: '\\twoheadleftarrow', value: '\\twoheadleftarrow' },
    { id: 35, name: '\\twoheadrightarrow', value: '\\twoheadrightarrow' },
    { id: 36, name: '\\leadsto', value: '\\leadsto' },
    { id: 37, name: '\\curvearrowright', value: '\\curvearrowright' },
    { id: 38, name: '\\curvearrowleft', value: '\\curvearrowleft' },
    { id: 39, name: '\\circlearrowright', value: '\\circlearrowright' },
    { id: 40, name: '\\circlearrowleft', value: '\\circlearrowleft' },
    { id: 41, name: '\\Leftarrow', value: '\\Leftarrow' },
    { id: 42, name: '\\Rightarrow', value: '\\Rightarrow' },
    { id: 43, name: '\\leftarrowtail', value: '\\leftarrowtail' },
    { id: 44, name: '\\rightarrowtail', value: '\\rightarrowtail' },
    { id: 45, name: '\\multimap', value: '\\multimap' },
    { id: 46, name: '\\leftrightsquigarrow', value: '\\leftrightsquigarrow' },
    { id: 47, name: '\\Lsh', value: '\\Lsh' },
    { id: 48, name: '\\Rsh', value: '\\Rsh' },
    { id: 49, name: '\\leftrightarrows', value: '\\leftrightarrows' },
    { id: 50, name: '\\leftrightarrow', value: '\\leftrightarrow' },
    { id: 51, name: '\\nLeftrightarrow', value: '\\nLeftrightarrow' },
    { id: 52, name: '\\Updownarrow', value: '\\Updownarrow' },
    { id: 53, name: '\\updownarrow', value: '\\updownarrow' },
    { id: 54, name: '\\Leftrightarrow', value: '\\Leftrightarrow' },
    { id: 55, name: '\\rightleftarrows', value: '\\rightleftarrows' },
    { id: 56, name: '\\rightleftharpoons', value: '\\rightleftharpoons' },
    { id: 57, name: '\\nRightarrow', value: '\\nRightarrow' },
    { id: 58, name: '\\nLeftarrow', value: '\\nLeftarrow' },
    { id: 59, name: '\\leftrightharpoons', value: '\\leftrightharpoons' },
    { id: 60, name: '\\Longleftarrow', value: '\\Longleftarrow' },
    { id: 61, name: '\\nleftrightarrow', value: '\\nleftrightarrow' },
    { id: 62, name: '\\nrightarrow', value: '\\nrightarrow' },
    { id: 63, name: '\\nleftarrow', value: '\\nleftarrow' },
    { id: 64, name: '\\Longleftrightarrow', value: '\\Longleftrightarrow' },
    { id: 65, name: '\\longleftrightarrow', value: '\\longleftrightarrow' },
    { id: 66, name: '\\Longrightarrow', value: '\\Longrightarrow' }
  ],

  operations: [
    { id: 1, name: 'x_a', value: 'x_a' },
    { id: 2, name: '{}^{a}x^{b}', value: '{^a x^b}' },
    { id: 3, name: 'x_{a}^{b}', value: '{x_a^b}' },
    { id: 4, name: 'x^b', value: 'x^b' },
    { id: 5, name: '{^a_b x^c_d}', value: '{^a_b x^c_d}' },
    { id: 6, name: '\\int_{a}^{b}', value: '\\intop\\nolimits_{a}^{b}' },
    { id: 7, name: '\\oint_{a}^{b}', value: '\\oint_{a}^{b}' },
    { id: 8, name: '\\oint', value: '\\oint' },
    { id: 9, name: '\\int', value: '\\int' },
    { id: 10, name: '\\iint_{a}^{b}', value: '\\iint_{a}^{b}' },
    { id: 11, name: '\\iint', value: '\\iint' },
    { id: 12, name: '\\iint_{a}^{b}', value: '\\iint\\nolimits_{a}^{b}' },
    { id: 13, name: '\\iiint', value: '\\iiint' },
    { id: 14, name: '\\sum_{a}^{b}', value: '\\sum\\nolimits_{a}^{b}' },
    { id: 15, name: '\\sum_{a}^{b}', value: '\\sum_{a}^{b}' },
    { id: 16, name: '\\sum', value: '\\sum' },
    { id: 17, name: '\\prod', value: '\\prod' },
    { id: 18, name: '\\prod_{a}^{b}', value: '\\prod_{a}^{b}' },
    {
      id: 19,
      name: '\\frac{d}{dx}',
      value: '\\frac{\\mathrm{d} }{\\mathrm{d} x}'
    },
    {
      id: 20,
      name: '\\frac{d^2}{dx^2}',
      value: '\\frac{\\mathrm{d^2} }{\\mathrm{d} x^2}'
    },
    {
      id: 21,
      name: '\\frac{\\partial}{\\partial x}',
      value: '\\frac{\\partial }{\\partial x}'
    },
    { id: 22, name: '\\sqrt[n]{x}', value: '\\sqrt[n]{x}' },
    { id: 23, name: '\\sqrt{x}', value: '\\sqrt{x}' },
    { id: 24, name: '\\small{\\lg}', value: '\\lg' },
    { id: 25, name: '\\small{\\ln}', value: '\\ln' },
    { id: 26, name: '\\small{\\log_{10}}', value: '\\log_{10}' },
    { id: 27, name: '\\small{\\log_{e}}', value: '\\log_{e}' },
    { id: 28, name: '\\small{\\lim_{x\\to 0}}', value: '\\lim_{x\\to 0}' },
    { id: 29, name: '\\small{\\max}', value: '\\max' },
    { id: 30, name: '\\small{\\min}', value: '\\min' },
    { id: 31, name: '\\small{\\sin}', value: '\\sin' },
    { id: 32, name: '\\small{\\arcsin}', value: '\\arcsin' },
    { id: 33, name: '\\small{\\sinh}', value: '\\sinh' },
    { id: 34, name: '\\small{\\csc}', value: '\\csc' },
    { id: 35, name: '\\small{\\cos}', value: '\\cos' },
    { id: 36, name: '\\small{\\cosh}', value: '\\cosh' },
    { id: 37, name: '\\small{\\arccos}', value: '\\arccos' },
    { id: 38, name: '\\small{\\sec}', value: '\\sec' },
    { id: 39, name: '\\small{\\tan}', value: '\\tan' },
    { id: 40, name: '\\small{\\arctan}', value: '\\arctan' },
    { id: 41, name: '\\small{\\tanh}', value: '\\tanh' },
    { id: 42, name: '\\small{\\cot}', value: '\\cot' },
    { id: 43, name: '\\small{\\coth}', value: '\\coth' }
  ],

  symbols: [
    { id: 1, name: '\\triangleright', value: '\\triangleright' },
    { id: 2, name: '\\triangleleft', value: '\\triangleleft' },
    { id: 3, name: '\\bigtriangledown', value: '\\bigtriangledown' },
    { id: 4, name: '\\bigtriangleup', value: '\\bigtriangleup' },
    { id: 5, name: '\\Box', value: '\\Box' },
    { id: 6, name: '\\lozenge', value: '\\lozenge' },
    { id: 7, name: '\\diamondsuit', value: '\\diamondsuit' },
    { id: 8, name: '\\boxtimes', value: '\\boxtimes' },
    { id: 9, name: '\\boxplus', value: '\\boxplus' },
    { id: 10, name: '\\boxminus', value: '\\boxminus' },
    { id: 11, name: '\\boxdot', value: '\\boxdot' },
    { id: 12, name: '\\bowtie', value: '\\bowtie' },
    { id: 13, name: '\\blacktriangleright', value: '\\blacktriangleright' },
    { id: 14, name: '\\blacktriangleleft', value: '\\blacktriangleleft' },
    { id: 15, name: '\\blacktriangledown', value: '\\blacktriangledown' },
    { id: 16, name: '\\blacktriangle', value: '\\blacktriangle' },
    { id: 17, name: '\\blacksquare', value: '\\blacksquare' },
    { id: 18, name: '\\blacklozenge', value: '\\blacklozenge' },
    { id: 19, name: '\\bigstar', value: '\\bigstar' },
    { id: 20, name: '\\star', value: '\\star' },
    { id: 21, name: '\\spadesuit', value: '\\spadesuit' },
    { id: 22, name: '\\ast', value: '\\ast' },
    { id: 23, name: '\\clubsuit', value: '\\clubsuit' },
    { id: 24, name: '\\bullet', value: '\\bullet' },
    { id: 25, name: '\\cdot', value: '\\cdot' },
    { id: 26, name: '\\ddagger', value: '\\ddagger' },
    { id: 27, name: '\\dotplus', value: '\\dotplus' },
    { id: 28, name: '\\dagger', value: '\\dagger' },
    { id: 29, name: '\\coprod', value: '\\coprod' },
    { id: 30, name: '\\curlyvee', value: '\\curlyvee' },
    { id: 31, name: '\\ulcorner', value: '\\ulcorner' },
    { id: 32, name: '\\gtrdot', value: '\\gtrdot' },
    { id: 33, name: '\\doublebarwedge', value: '\\doublebarwedge' },
    { id: 34, name: '\\dashv', value: '\\dashv' },
    { id: 35, name: '\\angle', value: '\\angle' },
    { id: 36, name: '\\cap', value: '\\cap' },
    { id: 37, name: '\\Cap', value: '\\Cap' },
    { id: 38, name: '\\measuredangle', value: '\\measuredangle' },
    { id: 39, name: '\\yen', value: '\\yen' },
    { id: 40, name: '\\S', value: '\\S' },
    { id: 41, name: '\\checkmark', value: '\\checkmark' },
    { id: 42, name: '\\emptyset', value: '\\emptyset' },
    { id: 43, name: '\\curlywedge', value: '\\curlywedge' },
    { id: 44, name: '\\urcorner', value: '\\urcorner' },
    { id: 45, name: '\\unrhd', value: '\\unrhd' },
    { id: 46, name: '\\unlhd', value: '\\unlhd' },
    { id: 47, name: '\\Finv', value: '\\Finv' },
    { id: 48, name: '\\bot', value: '\\bot' },
    { id: 49, name: '\\cup', value: '\\cup' },
    { id: 50, name: '\\Cup', value: '\\Cup' },
    { id: 51, name: '\\sphericalangle', value: '\\sphericalangle' },
    { id: 52, name: '\\circledast', value: '\\circledast' },
    { id: 53, name: '\\circledS', value: '\\circledS' },
    { id: 54, name: '\\circledR', value: '\\circledR' },
    { id: 55, name: '\\circ', value: '\\circ' },
    { id: 56, name: '\\oplus', value: '\\oplus' },
    { id: 57, name: '\\ominus', value: '\\ominus' },
    { id: 58, name: '\\oslash', value: '\\oslash' },
    { id: 59, name: '\\circleddash', value: '\\circleddash' },
    { id: 60, name: '\\varnothing', value: '\\varnothing' },
    { id: 61, name: '\\bigodot', value: '\\bigodot' },
    { id: 62, name: '\\bigcirc', value: '\\bigcirc' },
    { id: 63, name: '\\circledcirc', value: '\\circledcirc' }
  ],

  comparisons: [
    { id: 1, name: '\\leq', value: '\\leq' },
    { id: 2, name: '\\geq', value: '\\geq' },
    { id: 3, name: '\\neq', value: '\\neq' },
    { id: 4, name: '\\approx', value: '\\approx' },
    { id: 5, name: '\\equiv', value: '\\equiv' },
    { id: 6, name: '\\sim', value: '\\sim' },
    { id: 7, name: '\\doteq', value: '\\doteq' },
    { id: 8, name: '\\circeq', value: '\\circeq' },
    { id: 9, name: '\\cong', value: '\\cong' },
    { id: 10, name: '\\eqcirc', value: '\\eqcirc' },
    { id: 11, name: '\\Bumpeq', value: '\\Bumpeq' },
    { id: 12, name: '\\gvertneqq', value: '\\gvertneqq' },
    { id: 13, name: '\\ngeqslant', value: '\\ngeqslant' },
    { id: 14, name: '\\ngeqq', value: '\\ngeqq' },
    { id: 15, name: '\\ngeq', value: '\\ngeq' },
    { id: 16, name: '\\not\\equiv', value: '\\not\\equiv' },
    { id: 17, name: '\\backsim', value: '\\backsim' },
    { id: 18, name: '\\backsimeq', value: '\\backsimeq' },
    { id: 19, name: '\\eqsim', value: '\\eqsim' },
    { id: 20, name: '\\Doteq', value: '\\Doteq' },
    { id: 21, name: '\\fallingdotseq', value: '\\fallingdotseq' },
    { id: 22, name: '\\bumpeq', value: '\\bumpeq' },
    { id: 23, name: '\\gtrsim', value: '\\gtrsim' },
    { id: 24, name: '\\ngtr', value: '\\ngtr' },
    { id: 25, name: '\\eqslantgtr', value: '\\eqslantgtr' },
    { id: 26, name: '\\eqslantless', value: '\\eqslantless' },
    { id: 27, name: '\\gneqq', value: '\\gneqq' },
    { id: 28, name: '\\gtrless', value: '\\gtrless' },
    { id: 29, name: '\\gtrapprox', value: '\\gtrapprox' },
    { id: 30, name: '\\gnapprox', value: '\\gnapprox' },
    { id: 31, name: '\\asymp', value: '\\asymp' },
    { id: 32, name: '\\smile', value: '\\smile' },
    { id: 33, name: '\\frown', value: '\\frown' },
    { id: 34, name: '\\ll', value: '\\ll' },
    { id: 35, name: '\\gg', value: '\\gg' },
    { id: 36, name: '\\curlyeqprec', value: '\\curlyeqprec' },
    { id: 37, name: '\\curlyeqsucc', value: '\\curlyeqsucc' },
    { id: 38, name: '\\gtreqqless', value: '\\gtreqqless' },
    { id: 39, name: '\\gtreqless', value: '\\gtreqless' },
    { id: 40, name: '\\gneq', value: '\\gneq' }
  ],

  matrices: [
    {
      id: 1,
      name: '\\small \\begin{bmatrix} a & b & c \\\\ c & d & e \\\\ f & g & h \\end{bmatrix}',
      value:
        '\\begin{bmatrix}a & b & c \\\\ c & d & e \\\\ f & g & h \\end{bmatrix}'
    }
  ]
}
